version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=timerbackend
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - 'timerbackend-database:/var/lib/postgresql/data'
volumes:
    timerbackend-database:
        external: true
